version: '3'

services:
    go-app:
        image: golang:1.20
        container_name: go-app
        depends_on:
            - ticket-system1
        working_dir: /app
        command: sh -c "
            go build ./src/database/migrate &&
            cp -a . ../../app &&
            tail -F anything"
  
        expose:
            - '8000'
    ticket-system1:
        image: scylladb/scylla
        container_name: ticket-system1
        command: --smp 1
        environment:
            - 'SCYLLA_JMX_ADDR=-ja 0.0.0.0'
            - 'SCYLLA_JMX_REMOTE=-r'
        expose:
            - '7199'

    ticket-system2:
        image: scylladb/scylla
        container_name: ticket-system2
        command: --smp 1 --seeds=ticket-system1
        environment:
            - 'SCYLLA_JMX_ADDR=-ja 0.0.0.0'
            - 'SCYLLA_JMX_REMOTE=-r'
        expose:
            - '7199'

    ticket-system3:
        image: scylladb/scylla
        container_name: ticket-system3
        command: --smp 1 --seeds=ticket-system1
        environment:
            - 'SCYLLA_JMX_ADDR=-ja 0.0.0.0'
            - 'SCYLLA_JMX_REMOTE=-r'
        expose:
            - '7199'